'use strict';

import * as vscode from 'vscode';

export function getStandardOsgiHeaders(headerEnd: string) {
    return [
        new vscode.CompletionItem('Manifest-Version' + headerEnd),
        new vscode.CompletionItem('Created-By' + headerEnd),
        new vscode.CompletionItem('Signature-Version' + headerEnd),
        new vscode.CompletionItem('Class-Path' + headerEnd),
        new vscode.CompletionItem('Main-Class' + headerEnd),
        new vscode.CompletionItem('Implementation-Version' + headerEnd),
        new vscode.CompletionItem('Implementation-Vendor' + headerEnd),
        new vscode.CompletionItem('Implementation-Vendor-Id' + headerEnd),
        new vscode.CompletionItem('Implementation-URL' + headerEnd),
        new vscode.CompletionItem('Specification-Title' + headerEnd),
        new vscode.CompletionItem('Specification-Version' + headerEnd),
        new vscode.CompletionItem('Specification-Vendor' + headerEnd),
        new vscode.CompletionItem('Sealed' + headerEnd),
        new vscode.CompletionItem('Name' + headerEnd),
        new vscode.CompletionItem('Content-Type' + headerEnd),
        new vscode.CompletionItem('Java-Bean' + headerEnd),
        new vscode.CompletionItem('MD5-Digest' + headerEnd),
        new vscode.CompletionItem('SHA-Digest' + headerEnd),
        new vscode.CompletionItem('Magic' + headerEnd),
        new vscode.CompletionItem('Premain-Class' + headerEnd),
        new vscode.CompletionItem('Agent-Class' + headerEnd),
        new vscode.CompletionItem('Launcher-Agent-Class' + headerEnd),
        new vscode.CompletionItem('Boot-Class-Path' + headerEnd),
        new vscode.CompletionItem('Can-Redefine-Classes' + headerEnd),
        new vscode.CompletionItem('Can-Retransform-Classes' + headerEnd),
        new vscode.CompletionItem('Can-Set-Native-Method-Prefix' + headerEnd),
        new vscode.CompletionItem('Automatic-Module-Name' + headerEnd),
        new vscode.CompletionItem('Multi-Release' + headerEnd),
        // https://www.osgi.org/bundle-headers-reference/
        new vscode.CompletionItem('Bundle-ActivationPolicy' + headerEnd),
        new vscode.CompletionItem('Bundle-Activator' + headerEnd),
        new vscode.CompletionItem('Bundle-Category' + headerEnd),
        new vscode.CompletionItem('Bundle-Classpath' + headerEnd),
        new vscode.CompletionItem('Bundle-ContactAddress' + headerEnd),
        new vscode.CompletionItem('Bundle-Copyright' + headerEnd),
        new vscode.CompletionItem('Bundle-Description' + headerEnd),
        new vscode.CompletionItem('Bundle-DocURL' + headerEnd),
        new vscode.CompletionItem('Bundle-Icon' + headerEnd),
        new vscode.CompletionItem('Bundle-License' + headerEnd),
        new vscode.CompletionItem('Bundle-Localization' + headerEnd),
        new vscode.CompletionItem('Bundle-ManifestVersion' + headerEnd),
        new vscode.CompletionItem('Bundle-Name' + headerEnd),
        new vscode.CompletionItem('Bundle-NativeCode' + headerEnd),
        new vscode.CompletionItem('Bundle-RequiredExecutionEnvironment' + headerEnd),
        new vscode.CompletionItem('Bundle-SymbolicName' + headerEnd),
        new vscode.CompletionItem('Bundle-UpdateLocation' + headerEnd),
        new vscode.CompletionItem('Bundle-Vendor' + headerEnd),
        new vscode.CompletionItem('Bundle-Version' + headerEnd),
        new vscode.CompletionItem('DynamicImport-Package' + headerEnd),
        new vscode.CompletionItem('Eclipse-BuddyPolicy' + headerEnd),
        new vscode.CompletionItem('Eclipse-BuddBundleShapeyPolicy' + headerEnd),
        new vscode.CompletionItem('Eclipse-ExtensibleAPI' + headerEnd),
        new vscode.CompletionItem('Eclipse-PlatformFilter' + headerEnd),
        new vscode.CompletionItem('Eclipse-RegisterBuddy' + headerEnd),
        new vscode.CompletionItem('Export-Package' + headerEnd),
        new vscode.CompletionItem('Export-Service' + headerEnd),
        new vscode.CompletionItem('Fragment-Host' + headerEnd),
        new vscode.CompletionItem('Import-Bundle' + headerEnd),
        new vscode.CompletionItem('Import-Library' + headerEnd),
        new vscode.CompletionItem('Import-Package' + headerEnd),
        new vscode.CompletionItem('Import-Service' + headerEnd),
        new vscode.CompletionItem('Include-Resource	' + headerEnd),
        new vscode.CompletionItem('Module-Scope' + headerEnd),
        new vscode.CompletionItem('Module-Type' + headerEnd),
        new vscode.CompletionItem('Private-Package' + headerEnd),
        new vscode.CompletionItem('Provide-Capability' + headerEnd),
        new vscode.CompletionItem('Require-Bundle' + headerEnd),
        new vscode.CompletionItem('Require-Capability' + headerEnd),
        new vscode.CompletionItem('Web-ContextPath' + headerEnd),
        new vscode.CompletionItem('Web-DispatcherServletUrlPatterns' + headerEnd),
        new vscode.CompletionItem('Web-FilterMappings' + headerEnd),
    ];
}